Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy"  # Imagen base de la máquina virtual

  # Configuración de la máquina virtual
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"  # Agregar 4GB de RAM (4096MB)
  end

  # Provisión de Docker y Vagrant
  config.vm.provision "shell", inline: <<-SHELL
    # Actualizar los repositorios y paquetes existentes
    sudo apt-get update -y

    # Instalar las dependencias necesarias para Docker
    sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common

    # Agregar la clave GPG oficial de Docker
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

    # Agregar el repositorio estable de Docker
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu jammy stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    # Actualizar los repositorios nuevamente para incluir Docker
    sudo apt-get update -y

    # Instalar Docker
    sudo apt-get install -y docker-ce docker-ce-cli containerd.io

    # Agregar el usuario actual al grupo "docker" para ejecutar comandos de Docker sin sudo
    sudo usermod -aG docker vagrant

    # Instalar Vagrant
    sudo apt-get install -y vagrant
  SHELL
end
