Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy"
  config.vm.network "private_network", ip: "192.168.33.222"
  config.vm.network "public_network", ip: "10.1.1.227", bridge: "Realtek PCIe GBE Family Controller #2"
  config.vm.hostname = "jenkins"  
  config.vm.provider "virtualbox" do |vb|
    vb.name = "jenkins"
    vb.memory = "4096"
  end
  config.vm.provision "shell", path: "scripts/jenkins.sh"
end
